name: foo_app
description: Foo App
version: 0.0.1

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular: "^4.0.0+2"

dev_dependencies:
  dart_to_js_script_rewriter: ^1.0.1
  browser: any
transformers:
- angular:
    entry_points:
    - web/main.dart
- dart_to_js_script_rewriter

